---
- name: deploy lamp stack
  hosts: all
  become: true
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
         src: /home/vagrant/winners.sh
         dest: /home/vagrant/winners.sh
         owner: root
         group: root
         mode: '0755'

     - name: Copy cronjob with owner and permissions
       ansible.builtin.copy:
          src: /home/vagrant/cronscript.sh
          dest: /home/vagrant/cronscript.sh
          owner: root
          group: root
          mode: '0755'

      - name: Add cron job
        cron:
           name: uptime cron job
           minute: "0"
           hour: "0"
           user: root
           job: /home/vagrant/winners.sh
           state: present

       - name: install lamp stack and laravel
         script: /home/vagrant/winners.sh

